name: Build and Version Docker Image

on: pull_request

jobs:
  version-and-build:
  
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.number }}

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  
      - name: Get Latest Tag
        id: latest_tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
      - name: Set LATEST_TAG
        run: echo "LATEST_TAG=${{ steps.latest_tag.outputs.tag }}" >> $GITHUB_ENV
      - name: Generate Version
        id: generate_version
        run: |
          echo "The latest tag is: ${{ env.LATEST_TAG }}"
          VERSION_BASE=${LATEST_TAG//v/}
          RUN_NUMBER=$(($GITHUB_RUN_NUMBER))          
          FINAL_VERSION="${VERSION_BASE}-PR-${PR_NUMBER}-${RUN_NUMBER}-SNAPSHOT"      
          echo "FINAL_VERSION=$FINAL_VERSION" >> $GITHUB_ENV
          echo "Version generated: $FINAL_VERSION"
      # Step 4: Build the Docker image using Kaniko
      - name: Build Docker Image with Kaniko
        uses: gcr.io/kaniko-project/executor@v1.8.1
        with:
          image: gcr.io/my-docker-registry/my-org/${{ env.FINAL_VERSION }} 
          context: /workspace
          dockerfile: /workspace/Dockerfile
          buildargs: |
            VERSION=${{ env.FINAL_VERSION }} 
        env:
          DOCKER_CONFIG: /kaniko/.docker/
          KANIKO_FLAGS: '--cache=true'
          DOCKER_REGISTRY: gcr.io
          DOCKER_REGISTRY_ORG: my-org
          APP_NAME: my-app

