name: pull request comment
on:
  issue_comment:                                     
    types: [created, edited, deleted]
  pull_request:  # Trigger on any PR event (open, synchronize, closed, etc.)
jobs:
  run_pipeline:
    if: |
      contains(github.event.comment.body, '/retest') || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo say hello
