name: pull request comment
on: 
  issue_comment:                                     
    types: [created]
  pull_request:
jobs:
  run_pipeline:
    if: |
      contains(github.event.comment.body, '/retest') || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo say hello
