name: Release
on:
  push:
    branches:
      - main

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.8.1
          registry-url: https://npm.pkg.github.com/

      - name: Install dependencies
        run: |
          npm install
      - name: Install dependencies
        run: |
          npm install -g semantic-release @semantic-release/git @semantic-release/changelog
      - name: Install Commit Lint
        run: |
          npm install --save-dev @commitlint/config-conventional @commitlint/cli
      - name: Publish GitHub Package
        run: |
          npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # GITHUB_URL: https://github.com/TargetAU
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_CONFIG_REGISTRY: https://npm.pkg.github.com
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
