name: Semantic Version
on:
  push:
jobs:
  build:
    runs-on: tonline-ubuntu-m
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        npx semantic-release
        
