name: Semantic Version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      PR_NUMBER: ${{ github.event.number }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Fetch all tags
      run: git fetch --tags
    - name: Install dependencies
      run: |
        npm install -g semantic-release @semantic-release/git @semantic-release/changelog
    - name: Install Commit Lint
      run: |
        npm install --save-dev @commitlint/config-conventional @commitlint/cli
    - name: Run semantic-release
      run: npx semantic-release   
    - name: Get Latest Tag
      id: latest_tag
      uses: WyriHaximus/github-action-get-previous-tag@v1
    - name: Set LATEST_TAG
      run: echo "LATEST_TAG=${{ steps.latest_tag.outputs.tag }}" >> $GITHUB_ENV
    - name: Generate Version
      id: generate_version
      run: |
        echo "The latest tag is: ${{ env.LATEST_TAG }}"
        VERSION_BASE=${LATEST_TAG//v/}
        RUN_NUMBER=$(($GITHUB_RUN_NUMBER))
        FINAL_VERSION="${VERSION_BASE}-PR-${PR_NUMBER}-${RUN_NUMBER}-SNAPSHOT"          
        echo "FINAL_VERSION=$FINAL_VERSION" >> $GITHUB_ENV
        echo "Version generated: $FINAL_VERSION"
        
